# Project
sonar.projectKey=sailrc
sonar.projectName=sailrc
sonar.organization=processpuzzle
sonar.sourceEncoding=UTF-8
sonar.projectBaseDir=./
sonar.sources=src
sonar.exclusions=src/test-setup.ts, src/**/*.module.ts
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.eslint.reportPaths=reports/eslint/eslint.json
sonar.typescript.lcov.reportPaths=reports/coverage/lcov.info
