name: Build-SailRC
on:
  push:
    branches:
      - "feature/*"
    paths:
      - 'apps/sailrc/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - "develop"
    paths:
      - 'apps/sailrc/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    outputs:
      RUNNER: ${{ runner.name }}
    strategy:
      matrix:
        node-version: [ 22.x ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - id: lint-test-build
        name: Lint test and build the application
        uses: ZsZs/processpuzzle/.github/actions/lint-test-build@develop
        with:
          base_dir: 'apps/sailrc'
          nx_project: 'sailrc'
          github_token: ${{secrets.REPOSITORY_TOKEN}}
          sonar_token: ${{secrets.SONAR_TOKEN}}
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}

      - id: build-image
        name: Build and publish Docker images
        uses: ZsZs/processpuzzle/.github/actions/build-image@develop
        with:
          cicd_stage: 'ci'
          dockerhub_username: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: docker-compose
        name: run-docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './docker/docker-compose-ci.yaml'

      - id: e2e-test
        name: run-e2e-tests
        uses: ZsZs/processpuzzle/.github/actions/e2e-test@develop
        with:
          target_environment: 'ci'
